### ISSUE TITLE
i + 1 Changes from Previous - Proposal 

### ISSUE THREAD

**Issue by SandhiyaS24** [SKS2024SE/Unit_Conversion_2024#2]
1. Multilingual Support
Include support for English and Spanish using available APIs. This feature aligns with enhancing accessibility for users. Prioritizing English and Spanish for now is practical.
2. Text Enhancement 
Add functionality for enhancing or formatting text. This feature appears redundant for the project as it does not involve extensive text usage. I recommend omitting it unless future requirements demand otherwise.
3. Thesaurus
 Use APIs to add a thesaurus feature, possibly in a separate tab. While not directly related to unit conversion, this could be added as a separate feature if necessary. Suggest evaluating its relevance to the project goals.
4. Customizable Conversion 
Allow users to define custom conversion parameters. This feature seems partially implemented already. Clarification on the scope of "customizable" is needed to determine feasibility and implementation gaps.
5. Voice Input and Output - We can keep this a low-level priority as I feel this might complicate the project. If needed can we include this in the latter stages? 

Let me know your comments on this @Ks-Weasley  and @Sanjaeyss

**Comment by Ks-Weasley** [comment]
1. Multilingual support - Instead of Spanish, can we try to integrate Google Translate API so that multiple languages can be supported? 

3. Thesaurus - I do not know how this will be useful for a Unit converter.

**Comment by Sanjaeyss** [comment]
- Multilingual support makes sense to me, as discussed earlier, it would enable a variety of users to utilize the extension. 
- In my opinion, I see no need for a thesaurus for this application and especially not at this time. Maybe along the line when this application evolves into a Multi functional tool, rather than a conversion tool.

Lets Continue the work going on and See where it takes.
